#!/usr/bin/env python3

import argparse
import asyncio
import os
from src.actors.goblint import Goblint
from src.actors.dartagnan import Dartagnan
from src.actors.deagle import Deagle
from src.cooperace import Cooperace

parser = argparse.ArgumentParser()

parser.add_argument('--arch', required=False)
parser.add_argument('--prop', required=False)
parser.add_argument('--version', action='version', version='CoOpeRace 0.1')
parser.add_argument('filepath')

args = parser.parse_args()

abs_path = os.path.abspath(args.filepath) # to run outside benchexec
cooperace = Cooperace(abs_path, args.prop, args.arch)

def main():
    verdict = cooperace.runParallel([Goblint(), Dartagnan()])
    print("CoOpeRace verdict: " + verdict)

main()