#!/usr/bin/env python3

import argparse
import os
from src.cooperace import Cooperace

parser = argparse.ArgumentParser()

parser.add_argument('--arch', required=False)
parser.add_argument('--prop', required=False)
parser.add_argument('--version', action='version', version='CoOpeRace 0.1')
parser.add_argument('filepath')

args = parser.parse_args()

abs_path = os.path.abspath(args.filepath) # to run outside benchexec
cooperace = Cooperace(abs_path, args.prop, args.arch)

verdict = cooperace.start()
print("CoOpeRace verdict: " + verdict)
